

sStudies = bst_get('ProtocolStudies');

conditionNames = strings(numel(sStudies.Study),1);

for i = 1:numel(sStudies.Study)
    conditionNames(i) = string(sStudies.Study(i).Condition);
end

conditionNames = unique(conditionNames);
conditionNames = conditionNames(~startsWith(conditionNames,"@"));
disp(conditionNames);

% Get subjects in the cutrrent BST protocol
subjects_bst = bst_get('ProtocolSubjects') ; 
SubjectNames = {subjects_bst.Subject.Name};

% Removes Group analysis if any
SubjectNames(contains(SubjectNames,'Group')) = [] ; 



% Loop over each condition
for ii = 1:length(conditionNames)

    % Select current condition
    cond = conditionNames(ii);

    % Process: Select data files
    sFilesERP = bst_process('CallProcess', 'process_select_files_data', [], [], ...
        'subjectname',   [], ...
        'condition',     cond{1}, ...
        'tag',           '(#', ...
        'includebad',    0, ...
        'includeintra',  0, ...
        'includecommon', 0);

    %% -------------- ERP -----------------
    % Process: Average+Stderr: By folder (grand average)
    sFilesERPavg = bst_process('CallProcess', 'process_average', sFilesERP, [], ...
        'avgtype',       4, ...  % By folder (grand average)
        'avg_func',      7, ...  % Arithmetic average + Standard error
        'weighted',      0, ...
        'keepevents',    0);


    %% -------------- PSD ----------------
    
    sFilesPSD = bst_process('CallProcess', 'process_select_files_timefreq', sFilesERP, [], ...
                'subjectname',   [], ...
                'condition',     cond{1}, ...
                'tag',           'multiply', ...
                'includebad',    1, ...
                'includeintra',  0, ...
                'includecommon', 0);

    % Process: Average+Stderr: By folder (grand average)
    sFilesPSD = bst_process('CallProcess', 'process_average', sFilesPSD, [], ...
        'avgtype',       4, ...  % By folder (grand average)
        'avg_func',      7, ...  % Arithmetic average + Standard error
        'weighted',      0, ...
        'matchrows',     1, ...
        'iszerobad',     1);


    %% -------------- TF ----------------
    % Process: Time-frequency (Morlet wavelets)
    sFilesTF = bst_process('CallProcess', 'process_timefreq', sFilesERP, [], ...
        'sensortypes',   ' EEG', ...
        'edit',          struct(...
             'Comment',         'Power,1-90Hz', ...
             'TimeBands',       [], ...
             'Freqs',           [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90], ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'SaveKernel',      0), ...
        'normalize2020', 0, ...
        'normalize',     'none');  % None: Save non-standardized time-frequency maps

    % Process: Average: Everything
    sFilesTFavg = bst_process('CallProcess', 'process_average', sFilesTF, [], ...
        'avgtype',       1, ...  % Everything
        'avg_func',      1, ...  % Arithmetic average:  mean(x)
        'weighted',      0, ...
        'matchrows',     1, ...
        'iszerobad',     1);

    %% -------------- Alpha Phase ----------------
    
    
end