
% %% ----------------- Preprocessing ------------------
% % Process: Re-reference EEG
% sFiles = bst_process('CallProcess', 'process_eegref', sFiles, [], ...
%     'eegref',      'MASTOD, MASTOG', ...
%     'sensortypes', 'EEG');
% 
% 
% % Process: Band-pass:0.25Hz-95Hz
%         sFiles = bst_process('CallProcess', 'process_bandpass', sFiles, [], ...
%             'sensortypes', '', ...
%             'highpass',    0.25, ...
%             'lowpass',     95, ...
%             'tranband',    0, ...
%             'attenuation', 'strict', ...  % 60dB
%             'ver',         '2019', ...  % 2019
%             'mirror',      0, ...
%             'read_all',    0);
% 
% 
% % Process: Notch filter: 50Hz
% sFiles = bst_process('CallProcess', 'process_notch', sFiles, [], ...
%     'sensortypes', '', ...
%     'freqlist',    50, ...
%     'cutoffW',     3, ...
%     'useold',      0, ...
%     'read_all',    0);
% 
% % Process: ICA components: Picard
% sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
%     'timewindow',   [], ...
%     'eventname',    '', ...
%     'eventtime',    [-0.2, 0.2], ...
%     'sensortypes',  'EEG', ...
%     'ignorebad',    1, ...
%     'bandpass',     [0, 0], ...
%     'resample',     0, ...
%     'usessp',       1, ...
%     'method',       'picard', ...  % Picard:    Ablin, Cardoso & Gramfort (IEEE TSP 2018) 
%     'nicacomp',     32, ...
%     'icasort',      'VEOG', ...
%     'saveerp',      0);
% 


%% ---------------- Photocell correction -----------------

% This is for now only done on subSH, ii = 1; transform it then to a loop
% for all the participants

% Grabing all the preprocessed files
sFilesList = bst_process('CallProcess', 'process_select_files_data', [], [], ...
    'subjectname',   '', ...
    'condition',     '', ...
    'tag',           'Raw | band(0.25-95Hz) | notch(50Hz', ...
    'includebad',    0, ...
    'includeintra',  0, ...
    'includecommon', 0);



for ii = 1:length(sFilesList)

sFiles = {sFilesList(ii).FileName};
subName = extractBetween(sFilesList(ii).FileName, 1, 5);

% Process: Detect: stim1
sFiles = bst_process('CallProcess', 'process_evt_detect_analog', sFiles, [], ...
    'eventname',   'stim2', ...
    'channelname', 'Erg1', ...
    'timewindow',  [], ...
    'threshold',   2, ...
    'blanking',    1, ...
    'highpass',    0, ...
    'lowpass',     0, ...
    'refevent',    '200', ...
    'isfalling',   0, ...
    'ispullup',    0, ...
    'isclassify',  0);

% Process: Detect: stim1
sFiles = bst_process('CallProcess', 'process_evt_detect_analog', sFiles, [], ...
    'eventname',   'stim11', ...
    'channelname', 'Erg1', ...
    'timewindow',  [], ...
    'threshold',   2, ...
    'blanking',    1, ...
    'highpass',    0, ...
    'lowpass',     0, ...
    'refevent',    '110', ...
    'isfalling',   0, ...
    'ispullup',    0, ...
    'isclassify',  0);

% Process: Detect: stim1
sFiles = bst_process('CallProcess', 'process_evt_detect_analog', sFiles, [], ...
    'eventname',   'stim12', ...
    'channelname', 'Erg1', ...
    'timewindow',  [], ...
    'threshold',   2, ...
    'blanking',    1, ...
    'highpass',    0, ...
    'lowpass',     0, ...
    'refevent',    '120', ...
    'isfalling',   0, ...
    'ispullup',    0, ...
    'isclassify',  0);

% Process: Duplicate / merge events
sFiles = bst_process('CallProcess', 'process_evt_merge', sFiles, [], ...
    'evtnames', 'stim11,stim12', ...
    'newname',  'stim1', ...
    'delete',   1);

 % Process: Duplicate / merge events
sFiles = bst_process('CallProcess', 'process_evt_merge', sFiles, [], ...
    'evtnames', '10,20,30', ...
    'newname',  'cue', ...
    'delete',   1);

 % Process: Duplicate / merge events
sFiles = bst_process('CallProcess', 'process_evt_merge', sFiles, [], ...
    'evtnames', '15', ...
    'newname',  'resp', ...
    'delete',   1);

% Process: Delete events
sFiles = bst_process('CallProcess', 'process_evt_delete', sFiles, [], ...
    'eventname', '110,120,200');


sRaw = in_bst_data(sFilesList(ii).FileName);
% Get event labels
labels = string({sRaw.F.events.label});

% Find event markers to remove
mask = contains(labels, '_');

% Remove them
sRaw.F.events(mask) = [];

% ---- save once at the end ----
bst_save(file_fullpath(sFilesList(ii).FileName), sRaw, 'v6', 1);


%% ---------------- Adding trial identity to trigger --------------
% -------------- importing trialList --------------
filePath = fullfile('D:\DFF_data', subName, subName + ".csv");

T = readtable(filePath);

T = varfun(@string, T);

T.RespProbe = string(T{:,10} == T{:,5});

% all variation
% T.identity = string(T{:,4}) + "_" + ...
%               string(T{:,3}) + "_" + ...
%               string(T{:,6}) + "_" + ...
%               string(T{:,7}) + "_" + ...
%               string(T{:,9}) + "_" + ...
%               string(T{:,13});

% Temporal variation
T.identity = string(T{:,4}) + "_" + ...
              string(T{:,9});


% -------------- creating new events --------------
sRaw = in_bst_data(sFilesList(ii).FileName);

eventNames = {'stim1','stim2'};
for e = 1:numel(eventNames)

    % ---- extract event ----
    evtnew = sRaw.F.events(find(strcmp({sRaw.F.events.label}, eventNames{e}), 1));

    if isempty(evtnew)
        warning('Event %s not found', eventNames{e});
        continue
    end

    tnew  = evtnew.times;
    epnew = evtnew.epochs;

    % ---- choose grouping variable ----
    if eventNames{e} == "cue"
        groupingVar = T.identity;
    elseif eventNames{e} == "stim1"
        groupingVar = string(T{:,9}) + "_" + string(T{:,6});
    elseif eventNames{e} == "stim2"
        groupingVar =string(T{:,9}) + "_" + string(T{:,6});
    elseif eventNames{e} == "resp"
        groupingVar = string(T{:,9}) + "_" + string(T{:,13});
    end

    % ---- group ----
    [ulabels, ~, idx] = unique(groupingVar, 'stable');

    newEvents = repmat(evtnew, 1, numel(ulabels));

    for i = 1:numel(ulabels)
        sel = idx == i;

        newEvents(i).label  = char(eventNames{e} + "_" + ulabels(i));
        newEvents(i).times  = tnew(sel);
        newEvents(i).epochs = epnew(sel);
    end

    % ---- append ----
    sRaw.F.events = [sRaw.F.events, newEvents];

end

% ---- save once at the end ----
bst_save(file_fullpath(sFilesList(ii).FileName), sRaw, 'v6', 1);


%% ----------------- Epoch computing --------------------------------
% Process: Import MEG/EEG: Events
labels = {sRaw.F.events.label}; labels = string(labels);

mask = contains(labels, '_');
EventsMarkers = labels(mask);




% Loop through conditions 
    for iCond=1:length(EventsMarkers)

        if contains(EventsMarkers{iCond}, 'cue')
            Epoch = [-0.5,1.5];
            Epoch_baseline = [-0.5,0];
        else
            Epoch = [-0.5,0.5];
            Epoch_baseline = [-0.5,0];
        end
            % Process: Import MEG/EEG: Events
            sFilesEpochs = bst_process('CallProcess', 'process_import_data_event', ...
                {sFilesList(ii).FileName} , [], ...   
                'subjectname',   subName{1}, ... % 1 out of 1
                'condition',     EventsMarkers{iCond}, ...
                'eventname',     EventsMarkers{iCond}, ...
                'timewindow',    [], ...
                'epochtime',     Epoch, ...
                'split',         0, ...
                'createcond',    1, ...
                'ignoreshort',   1, ...
                'usectfcomp',    1, ...
                'usessp',        1, ...
                'freq',          [], ...
                'baseline',      Epoch_baseline, ...
                'blsensortypes', 'MEG, EEG');

            % % average for ERP analysis
            %  avg_sFilesEpochs = bst_process(...
            %     'CallProcess', 'process_average', ...
            %     sFilesEpochs, [], ...
            %     'avgtype', 4, ...
            %     'avg_func', 1, ...  
            %     'keepevents', 0);

            %% -------------- ERP -----------------
            % Process: Average+Stderr: By folder (grand average)
            ERPsFilesEpochs = bst_process('CallProcess', 'process_average', sFilesEpochs, [], ...
                'avgtype',       4, ...  % By folder (grand average)
                'avg_func',      7, ...  % Arithmetic average + Standard error
                'weighted',      0, ...
                'keepevents',    0);
        
            % % Process: Z-score transformation: [-400ms,-2ms]
            % ERPsFilesEpochsNorm = bst_process('CallProcess', 'process_baseline_norm', ERPsFilesEpochs, [], ...
            %     'baseline',    [-0.4004, -0.002], ...
            %     'sensortypes', 'MEG, EEG', ...
            %     'method',      'zscore', ...  % Z-score transformation:    x_std = (x - &mu;) / &sigma;
            %     'overwrite',   0);

            % PSD analysis
            PSDsFilesEpochs = bst_process('CallProcess', 'process_psd', sFilesEpochs, [], ...
                'timewindow',  Epoch, ...
                'win_length',  0.8, ...
                'win_overlap', 30, ...
                'units',       'physical', ...  % Physical: U2/Hz
                'sensortypes', 'EEG', ...
                'win_std',     0, ...
                'edit',        struct(...
                 'Comment',         'Avg,Power', ...
                 'TimeBands',       [], ...
                 'Freqs',           [], ...
                 'ClusterFuncTime', 'none', ...
                 'Measure',         'power', ...
                 'Output',          'average', ...
                 'SaveKernel',      0));

            % Process: Spectrum normalization
            PSDsFilesEpochsMultiply = bst_process('CallProcess', 'process_tf_norm', PSDsFilesEpochs, [], ...
                'normalize', 'multiply2020', ...  % 1/f compensation (multiply power by frequency)
                'overwrite', 0);
    end
end